### ISSUE TITLE
Can connect to graph - but cannot query?

### ISSUE THREAD

**Issue by danpaulsmith** [yWorks/yfiles-neo4j-basic-demo#1]
16:46:41 Connecting to bolt://bolt.*******.ai:30001...
16:46:42 Connection successful.
16:46:42 Connecting to bolt://bolt.*******.ai:30001...
16:46:43 Connection successful.
16:46:49 Query failed:
16:46:49 MATCH (()-[r:`*******`]->()) WITH r LIMIT 1000 UNWIND keys(r) as key RETURN
16:46:49 "*******" as label, collect(distinct key) as keys
16:46:49 params: {}
16:46:49 Failed to establish connection in 5000ms
16:46:49 getAllRelationshipProperties failed
16:46:49 Cannot read property 'records' of undefined
16:46:49 Query failed:
16:46:49 MATCH (()-[r:`*******`]->()) WITH r LIMIT 1000 UNWIND keys(r) as key RETURN "*******" as
16:46:49 label, collect(distinct key) as keys
16:46:49 params: {}
16:46:49 Failed to establish connection in 5000ms
16:46:49 Query failed:
16:46:49 MATCH (()-[r:`*******`]->()) WITH r LIMIT 1000 UNWIND keys(r) as key RETURN "*******" as
16:46:49 label, collect(distinct key) as keys
16:46:49 params: {}
16:46:49 Failed to establish connection in 5000ms
16:46:49 Query failed:
16:46:49 MATCH (()-[r:`*******`]->()) WITH r LIMIT 1000 UNWIND keys(r) as key RETURN "*******" as label,
16:46:49 collect(distinct key) as keys
16:46:49 params: {}
16:46:49 Failed to establish connection in 5000ms
16:46:49 Query failed:
16:46:49 MATCH (()-[r:`*******`]->()) WITH r LIMIT 1000 UNWIND keys(r) as key RETURN "*******"
16:46:49 as label, collect(distinct key) as keys
16:46:49 params: {}
16:46:49 Failed to establish connection in 5000ms
16:46:49 Query failed:
16:46:49 MATCH (()-[r:`*******`]->()) WITH r LIMIT 1000 UNWIND keys(r) as key RETURN
16:46:49 "*******" as label, collect(distinct key) as keys
16:46:49 params: {}
16:46:49 Failed to establish connection in 5000ms
16:46:49 Query failed:
16:46:49 MATCH (()-[r:`*******`]->()) WITH r LIMIT 1000 UNWIND keys(r) as key RETURN "*******" as
16:46:49 label, collect(distinct key) as keys
16:46:49 params: {}
16:46:49 Failed to establish connection in 5000ms
16:46:49 Query failed:
16:46:49 MATCH (()-[r:`*******`]->()) WITH r LIMIT 1000 UNWIND keys(r) as key RETURN "*******" as label,
16:46:49 collect(distinct key) as keys
16:46:49 params: {}
16:46:49 Failed to establish connection in 5000ms
16:46:49 Query failed:
16:46:49 MATCH (()-[r:`*******`]->()) WITH r LIMIT 1000 UNWIND keys(r) as key RETURN
16:46:49 "*******" as label, collect(distinct key) as keys
16:46:49 params: {}
16:46:49 Failed to establish connection in 5000ms
16:46:49 Query failed:
16:46:49 MATCH (()-[r:`*******`]->()) WITH r LIMIT 1000 UNWIND keys(r) as key RETURN "*******" as
16:46:49 label, collect(distinct key) as keys
16:46:49 params: {}
16:46:49 Failed to establish connection in 5000ms
16:46:49 Query failed:
16:46:49 MATCH (()-[r:`*******`]->()) WITH r LIMIT 1000 UNWIND keys(r) as key RETURN
16:46:49 "*******" as label, collect(distinct key) as keys
16:46:49 params: {}
16:46:49 Failed to establish connection in 5000ms
16:46:49 Query failed:
16:46:49 MATCH (()-[r:`*******`]->()) WITH r LIMIT 1000 UNWIND keys(r) as key RETURN
16:46:49 "*******" as label, collect(distinct key) as keys
16:46:49 params: {}
16:46:49 Failed to establish connection in 5000ms
16:46:49 Query failed:
16:46:49 MATCH (()-[r:`*******`]->()) WITH r LIMIT 1000 UNWIND keys(r) as key RETURN "*******" as label,
16:46:49 collect(distinct key) as keys
16:46:49 params: {}
16:46:49 Failed to establish connection in 5000ms
16:46:51 Fetching schema failed!
16:46:51 Cannot read property '*******' of undefined

**Comment by yGuy** [comment]
Hmm - do you have reasons to believe that this is due to an issue with the demo code? I mean, this is all just a simple call to the bolt driver. Either this is an issue with the database (query indeed takes too long to execute and the timeout needs to be adjusted in the demo code), or with the bolt driver, but I fail to see how this is related to rest of the code in the demo. Do those queries execute normally and finish well under 5 seconds in neo4j desktop?

**Comment by danpaulsmith** [comment]
thanks, yes fair point, I assumed as the connection to the graph was successful, it was an issue with how it was being queried, but I'll increase the timeout, as 5000ms does seem a little too short for the graph I'm using. I'll post back an update

**Comment by yGuy** [comment]
Is this actually output from the [Neo4j Explorer](https://www.yworks.com/neo4j-explorer/)? This repo is *not* about the explorer app. It's about a very simple app that developers can use as a starting point to create their own applications using [the javascript graph library yFiles for HTML](https://yworks.com/yfileshtml). If this is in the explorer, I will need to check whether the timeout can be configured at all. How long does executing these queries take in the neo4j browser app?

**Comment by yGuy** [comment]
I'm closing this as unrelated. Feel free to reopen or comment if you have more input.
